export const categoryInfo = [
  {
    id: 1,
    name: 'Бизнес-книги',
    amount: '14',
    path: '/business',
  },
  {
    id: 2,
    name: 'Детективы',
    amount: '8',
    path: '/detective',
  },
  {
    id: 3,
    name: 'Детские книги',
    amount: '10',
    path: '/children',
  },
  {
    id: 4,
    name: 'Зарубежная литература',
    amount: '2',
    path: '/foreign',
  },
  {
    id: 5,
    name: 'История',
    amount: '5',
    path: '/history',
  },
  {
    id: 6,
    name: 'Классическая литература',
    amount: '12',
    path: '/classic',
  },
  {
    id: 7,
    name: 'Книги по психологии',
    amount: '11',
    path: '/psihology',
  },
  {
    id: 8,
    name: 'Компьютерная литература',
    amount: '54',
    path: '/computer',
  },
  {
    id: 9,
    name: 'Культура и искусство',
    amount: '0',
    path: '/culture',
  },
  {
    id: 10,
    name: 'Наука и образование',
    amount: '2',
    path: '/science',
  },
  {
    id: 11,
    name: 'Публицистическая литература',
    amount: '0',
    path: '/journalistic',
  },
  {
    id: 12,
    name: 'Справочники',
    amount: '10',
    path: '/directories',
  },
  {
    id: 13,
    name: 'Фантастика',
    amount: '12',
    path: '/fantastic',
  },
  {
    id: 14,
    name: 'Юмористическая литература',
    amount: '8',
    path: '/humor',
  },
];
